#!/bin/sh
set -e
package_name=plymouth-nvidia
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/etc/modprobe.d/nvidia.conf"
    dpkg-divert --package "$package_name" --rename --remove "/etc/initramfs-tools/modules"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/etc/modprobe.d/nvidia.conf"
    dpkg-divert --package "$package_name" --rename --remove "/etc/initramfs-tools/modules"
;;
esac
exit 0
